--==========================================================
--  ZINKA LOADER (English) — readable source
--  Build: node tools/obfuscate.js  →  loader.lua / dist/loader.lua
--  Secrets: numeric fragments + runtime XOR (no plaintext URLs in ship build).
--  Work.ink LINK_ID / OWNER reconstructed arithmetically; Discord UI disabled.
--==========================================================

--== opaque string vault (XOR rolling key, fragments assembled at runtime) ==--
local function _bx(a, b)
    if bit32 then return bit32.bxor(a, b) end
    local r, p = 0, 1
    for _ = 1, 8 do
        if a % 2 ~= b % 2 then r = r + p end
        a, b, p = math.floor(a / 2), math.floor(b / 2), p * 2
    end
    return r
end

-- key fragments mixed with junk (real key = K1..K3 concat, skip junk slots)
local _K1 = {0x5A, 0xC3, 0x91, 0x2E}
local _K2 = {0x77, 0xB4, 0x08, 0xD1}
local _K3 = {0x3F, 0x6A, 0xE2, 0x19}
local _KJ = {0x11, 0x22, 0x33} -- decoy, unused

local function _mk()
    local k = {}
    for _, p in ipairs({_K1, _K2, _K3}) do
        for i = 1, #p do k[#k + 1] = p[i] end
    end
    return k
end

local function _xd(bytes)
    local key = _mk()
    local kl = #key
    local out = table.create and table.create(#bytes) or {}
    local a = 0x5A
    for i = 1, #bytes do
        local k = key[((i - 1) % kl) + 1]
        local plain = _bx(_bx(_bx(bytes[i], k), a % 256), ((i - 1) * 31) % 256)
        out[i] = string.char(plain)
        a = (a + bytes[i] + k) % 256
    end
    return table.concat(out)
end

-- Pre-encoded with same rolling XOR as tools/obfuscate.js (xorEncrypt).
-- Regenerated by: node -e "..." or tools/gen-enc-strings.js (rolling variant below).
-- Built inline so source has no cleartext URLs.
local function _enc(s)
    local key = _mk()
    local kl = #key
    local out = {}
    local a = 0x5A
    for i = 1, #s do
        local byte = string.byte(s, i)
        local k = key[((i - 1) % kl) + 1]
        local x = _bx(_bx(_bx(byte, k), a % 256), ((i - 1) * 31) % 256)
        out[i] = x
        a = (a + x + k) % 256
    end
    return out
end

-- Build vault once (values computed at load; never appear as string literals in this file).
-- Construction uses only number tables so grepping the file finds no https://work.ink etc.
local function _join(parts)
    local t = {}
    for _, p in ipairs(parts) do
        for i = 1, #p do t[#t + 1] = p[i] end
    end
    return t
end

-- Char-code fragments (split so no contiguous readable URL)
local function _cs(t)
    local o = {}
    for i = 1, #t do o[i] = string.char(t[i]) end
    return table.concat(o)
end

-- Assemble sensitive strings from numeric fragments only
local S_HTTPS = _cs({104, 116, 116, 112, 115, 58, 47, 47})
local S_WORK = _cs({119, 111, 114, 107, 46, 105, 110, 107})
local S_API_PATH = _cs({47, 95, 97, 112, 105, 47, 118, 50, 47, 116, 111, 107, 101, 110, 47, 105, 115, 86, 97, 108, 105, 100, 47})
local S_KEYPATH = _cs({47, 50, 113, 81, 101, 47, 122, 105, 110, 107, 97, 45, 107, 101, 121})
local S_RAW = _cs({114, 97, 119, 46, 103, 105, 116, 104, 117, 98, 117, 115, 101, 114, 99, 111, 110, 116, 101, 110, 116, 46, 99, 111, 109})
local S_REPO = _cs({47, 115, 116, 97, 115, 105, 107, 115, 50, 49, 50, 51, 50, 52, 47, 114, 110, 45, 115, 99, 114, 105, 112, 116, 115, 47, 109, 97, 105, 110, 47, 122, 105, 110, 107, 97})
local S_DISC_HOST = _cs({100, 105, 115, 99, 111, 114, 100, 46, 103, 103})
local S_DISC_PATH = _cs({47, 100, 53, 70, 78, 69, 89, 84, 118, 98, 121})
local S_KEYFILE = _cs({114, 97, 121, 111, 110, 95, 107, 101, 121, 46, 116, 120, 116})
-- auth salt v3: token includes device hwid hash
local S_SALT = _cs({122, 105, 110, 107, 97, 46, 114, 110, 46, 97, 117, 116, 104, 46, 118, 51})
-- session salt v1: loader-minted nonce signature (anti direct-inject of main script)
local S_SESS = _cs({122, 105, 110, 107, 97, 46, 114, 110, 46, 115, 101, 115, 115, 46, 118, 49})
local S_NAME = _cs({90, 73, 78, 75, 65})
-- local bind fallback file (when Worker/KV not ready)
local S_BINDFILE = _cs({114, 97, 121, 111, 110, 95, 98, 105, 110, 100, 46, 116, 120, 116})
-- Worker origin for /bind (no trailing slash). EMPTY until you deploy worker.js —
-- then set char-codes to e.g. https://YOUR-NAME.YOUR-SUBDOMAIN.workers.dev
-- and rebuild. If SCRIPT_URL already points at *.workers.dev, bind uses that host.
local S_WORKER = _cs({})

-- Second layer: XOR-pack assembled strings so even fragment concat isn't left as plaintext locals after minify
local E_SCRIPT = _enc(S_HTTPS .. S_RAW .. S_REPO)
local E_KEYLINK = _enc(S_HTTPS .. S_WORK .. S_KEYPATH)
local E_API = _enc(S_HTTPS .. S_WORK .. S_API_PATH)
local E_DISCORD = _enc(S_HTTPS .. S_DISC_HOST .. S_DISC_PATH)
local E_KEYFILE = _enc(S_KEYFILE)
local E_SALT = _enc(S_SALT)
local E_SESS = _enc(S_SESS)
local E_NAME = _enc(S_NAME)
local E_BINDFILE = _enc(S_BINDFILE)
local E_WORKER = _enc(S_WORKER)

-- wipe plaintext assemblers
S_HTTPS, S_WORK, S_API_PATH, S_KEYPATH, S_RAW, S_REPO = nil, nil, nil, nil, nil, nil
S_DISC_HOST, S_DISC_PATH, S_KEYFILE, S_SALT, S_SESS, S_NAME = nil, nil, nil, nil, nil, nil
S_BINDFILE, S_WORKER = nil, nil

local function secret(which)
    if which == 1 then return _xd(E_SCRIPT)
    elseif which == 2 then return _xd(E_KEYLINK)
    elseif which == 3 then return _xd(E_API)
    elseif which == 4 then return _xd(E_DISCORD)
    elseif which == 5 then return _xd(E_KEYFILE)
    elseif which == 6 then return _xd(E_SALT)
    elseif which == 7 then return _xd(E_NAME)
    elseif which == 8 then return _xd(E_WORKER)
    elseif which == 9 then return _xd(E_BINDFILE)
    elseif which == 10 then return _xd(E_SESS)
    end
    return ""
end

-- Numeric IDs split (arithmetic reconstitution — no full PlaceId literal)
local function linkId()
    return (4800 * 1000) + 430 -- 4800430
end
local function ownerId()
    return (579 * 1000) + 838 -- 579838
end
-- Violence District / Район насилия — add more via placeIdN() + ALLOWED_PLACES
local function placeId()
    -- fragments only (hi * 1e6 + lo); full id never as a single literal
    local hi = (9000 + 397) * 10000 + 8595
    local lo = (700 + 33) * 1000 + 734
    return hi * 1000000 + lo
end
-- session magic (loader mint); reconstituted arithmetically
local function sessMagic()
    return ((0x5A17 * 65536) + 0xC0DE)
end

local CONFIG = {
    NAME = secret(7),
    SCRIPT_URL = secret(1),
    BUST_CACHE = true,
    KEY_LINK = secret(2),
    OWNER_USER_ID = ownerId(),
    LINK_ID = linkId(),
    -- configurable allowlist: [placeId()] = display name, add more entries as needed
    ALLOWED_PLACES = {
        [placeId()] = "[Treatment] Violence District",
    },
    KICK_ON_WRONG_PLACE = true,
    KICK_ON_NO_KEY = true,
    KEY_FILE = secret(5),
    BIND_FILE = secret(9),
    -- Cloudflare Worker origin for /bind (empty until deployed; may also come from SCRIPT_URL host)
    WORKER_ORIGIN = secret(8),
    -- Discord invite (encrypted); button is intentionally non-functional for now
    DISCORD_INVITE = secret(4),
    DISCORD_ENABLED = false,
}

--== double-run guard ==--
local genv = (getgenv and getgenv()) or _G
if genv.__RN_LOADER_RUNNING then
    return warn("[" .. CONFIG.NAME .. "] Already running.")
end
genv.__RN_LOADER_RUNNING = true

--== services ==--
local Players = game:GetService("Players")
local HttpService = game:GetService("HttpService")
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")
local UIS = game:GetService("UserInputService")
local GuiService = game:GetService("GuiService")
local StarterGui = game:GetService("StarterGui")
local lp = Players.LocalPlayer or Players.PlayerAdded:Wait()

local ACCEPTED_KEY = nil
local DEVICE_HWID = nil -- hashed binding id (never raw executor HWID in auth blob)
local API_PREFIX = secret(3)
local AUTH_SALT = secret(6)
local SESS_SALT = secret(10)
local SESS_MAGIC = sessMagic()

--== device fingerprint (HWID → ClientId → UserId) ==--
local function rawDeviceId()
    local probes = {
        function() return gethwid and gethwid() end,
        function() return get_hwid and get_hwid() end,
        function() return getHWID and getHWID() end,
        function() return syn and syn.get_hwid and syn.get_hwid() end,
        function() return syn and syn.gethwid and syn.gethwid() end,
        function() return fluxus and fluxus.get_hwid and fluxus.get_hwid() end,
        function()
            local ok, svc = pcall(function() return game:GetService("RbxAnalyticsService") end)
            if ok and svc and svc.GetClientId then return svc:GetClientId() end
        end,
        function()
            if lp and lp.UserId and lp.UserId > 0 then
                return "uid:" .. tostring(lp.UserId)
            end
        end,
    }
    for _, fn in ipairs(probes) do
        local ok, v = pcall(fn)
        if ok and v ~= nil then
            local s = tostring(v):gsub("%s+", "")
            if #s >= 4 and s ~= "nil" and s ~= "0" then return s end
        end
    end
    return "fallback:" .. tostring(game.PlaceId) .. ":" .. tostring(os.time() % 100000)
end

--== cheap token (no HTTP): hash key+salt+ts+hwid fragments ==--
local function mix32(n)
    n = (n * 1664525 + 1013904223) % 4294967296
    return n
end

local function hashHwid(raw)
    local h = 2166136261
    local s = tostring(raw) .. "|" .. AUTH_SALT .. "|hwid"
    for i = 1, #s do
        h = mix32(_bx(h % 256, string.byte(s, i)) + math.floor(h / 256) + i * 131)
    end
    return string.format("%08x%08x", h % 4294967296, mix32(h + #s) % 4294967296)
end

local function getDeviceHwid()
    if DEVICE_HWID then return DEVICE_HWID end
    DEVICE_HWID = hashHwid(rawDeviceId())
    return DEVICE_HWID
end

local function tokenOf(key, ts, hid)
    local h = 2166136261
    local s = tostring(key) .. "|" .. AUTH_SALT .. "|" .. tostring(ts) .. "|"
        .. tostring(game.PlaceId) .. "|" .. tostring(hid or "")
    for i = 1, #s do
        h = mix32(_bx(h % 256, string.byte(s, i)) + math.floor(h / 256) + i * 131)
    end
    return string.format("%08x%08x", h % 4294967296, mix32(h + #s) % 4294967296)
end

-- loader-only session signature (nonce + magic); main script rejects blobs without valid s/n
local function sessionSig(key, ts, hid, nonce)
    local h = 2166136261
    local s = tostring(key) .. "|" .. SESS_SALT .. "|" .. tostring(ts) .. "|"
        .. tostring(hid or "") .. "|" .. tostring(nonce) .. "|" .. tostring(SESS_MAGIC)
        .. "|" .. tostring(game.PlaceId)
    for i = 1, #s do
        h = mix32(_bx(h % 256, string.byte(s, i)) + math.floor(h / 256) + i * 173)
    end
    return string.format("%08x%08x", h % 4294967296, mix32(h + #s + SESS_MAGIC) % 4294967296)
end

local function mintNonce(ts, key)
    local a = mix32(ts * 2654435761 + #tostring(key))
    local b = mix32(math.floor((os.clock() % 1) * 1e9) + a)
    return string.format("%08x%08x", a % 4294967296, b % 4294967296)
end

local function publishAuth(key)
    local ts = os.time()
    local hid = getDeviceHwid()
    local tok = tokenOf(key, ts, hid)
    local nonce = mintNonce(ts, key)
    local sess = sessionSig(key, ts, hid, nonce)
    local blob = {
        k = key,
        ts = ts,
        t = tok,
        h = hid,
        lid = CONFIG.LINK_ID,
        n = nonce, -- per-load session nonce
        s = sess,  -- session signature (requires loader mint path)
        -- integrity mirror (script re-derives; decoy field confuses strippers)
        _ = mix32(ts + #key),
    }
    genv.__RN_AUTH = blob
    _G.__RN_AUTH = blob
    genv.__RN_AUTH_OK = true
    _G.__RN_AUTH_OK = true
    genv.__RN_HWID = hid
    _G.__RN_HWID = hid
    genv.__RN_LOADER = true -- real loader mark (main checks shape, not this alone)
    _G.__RN_LOADER = true
    -- decoys: look legitimate, never consulted by real gates
    genv.__RN_OK = true
    genv.__RN_AUTH_SOFT = { ok = true, t = tok }
    genv.__ZINKA_PREAUTH = "ok"
    genv.__RN_AUTH_TOKEN = string.format("%08x", mix32(ts))
    _G.__RN_OK = true
    _G.__RN_AUTH_SOFT = genv.__RN_AUTH_SOFT
    _G.__ZINKA_PREAUTH = "ok"
    _G.__RN_AUTH_TOKEN = genv.__RN_AUTH_TOKEN
end

local function workerOrigin()
    local explicit = tostring(CONFIG.WORKER_ORIGIN or ""):gsub("%s+", ""):gsub("/+$", "")
    if #explicit > 12 then return explicit end
    local su = tostring(CONFIG.SCRIPT_URL or "")
    local host = su:match("^(https://[%w%-%.]+%.workers%.dev)")
    return host
end

-- Local bind fallback (weak — same machine FS only). Real enforcement = Worker KV.
local function localBindCheck(key, hid)
    if not hasFS then return true end
    local path = CONFIG.BIND_FILE
    local map = {}
    pcall(function()
        if isfile(path) then
            for line in string.gmatch(readfile(path), "[^\r\n]+") do
                local k, h = line:match("^([^%s|]+)|([0-9a-fA-F]+)$")
                if k and h then map[k:lower()] = h:lower() end
            end
        end
    end)
    local prev = map[key:lower()]
    if prev and prev ~= hid:lower() then
        return false, "Key already bound to another device"
    end
    map[key:lower()] = hid:lower()
    local lines = {}
    for k, h in pairs(map) do
        lines[#lines + 1] = k .. "|" .. h
    end
    pcall(writefile, path, table.concat(lines, "\n"))
    return true
end

-- Remote bind via Cloudflare Worker; falls back to local if Worker/KV missing.
local function bindDevice(key)
    local hid = getDeviceHwid()
    local origin = workerOrigin()
    if origin then
        local uid = (lp and lp.UserId) and tostring(lp.UserId) or "0"
        local url = origin .. "/bind?k=" .. HttpService:UrlEncode(key)
            .. "&h=" .. HttpService:UrlEncode(hid)
            .. "&u=" .. HttpService:UrlEncode(uid)
        local body = httpGet(url)
        if type(body) == "string" then
            body = body:gsub("^%s+", ""):gsub("%s+$", "")
            if body == "OK" then return true end
            local reason = body:match("^DENIED:(%w+)")
            if reason == "bound" then
                return false, "Key already bound to another device"
            end
            if reason == "noconfig" then
                -- KV not bound yet — soft fallback
                return localBindCheck(key, hid)
            end
            if reason == "invalid" or reason == "expired" or reason == "foreign" or reason == "badkey" then
                return false, "Key is invalid or expired"
            end
            if reason == "badhwid" then
                return false, "Device id unavailable — try another executor"
            end
            if reason then
                return false, "Bind rejected: " .. reason
            end
        end
        -- Worker unreachable: do not block activation; local + hwid-in-token still apply
        return localBindCheck(key, hid)
    end
    return localBindCheck(key, hid)
end

--== utils ==--
local function notify(text, dur)
    pcall(function()
        StarterGui:SetCore("SendNotification", {
            Title = CONFIG.NAME, Text = text, Duration = dur or 5,
        })
    end)
end

local function stop(reason, kick)
    genv.__RN_LOADER_RUNNING = nil
    warn(("[%s] %s"):format(CONFIG.NAME, reason))
    if kick then
        task.delay(0.4, function()
            pcall(function() lp:Kick(("[%s]\n\n%s"):format(CONFIG.NAME, reason)) end)
        end)
    else
        notify(reason, 8)
    end
    error(reason, 0)
end

local function httpGet(url)
    local tries = {
        function() return game:HttpGet(url, true) end,
        function() return game:HttpGetAsync(url, true) end,
        function()
            local req = (syn and syn.request) or http_request or request
            return req and req({ Url = url, Method = "GET" }).Body
        end,
    }
    for _, fn in ipairs(tries) do
        local ok, res = pcall(fn)
        if ok and type(res) == "string" and #res > 0 then return res end
    end
    return nil
end

local hasFS = (readfile and writefile and isfile) ~= nil
local function loadSavedKey()
    if not hasFS then return nil end
    local ok, data = pcall(function()
        if isfile(CONFIG.KEY_FILE) then return readfile(CONFIG.KEY_FILE) end
    end)
    return ok and data or nil
end
local function saveKey(key)
    if hasFS then pcall(writefile, CONFIG.KEY_FILE, key) end
end
local function clearKey()
    if hasFS then pcall(function() if isfile(CONFIG.KEY_FILE) then delfile(CONFIG.KEY_FILE) end end) end
end

--==========================================================
--  PLACE CHECK
--==========================================================
if not game:IsLoaded() then game.Loaded:Wait() end

local placeName = CONFIG.ALLOWED_PLACES[game.PlaceId]
if not placeName then
    local list = {}
    for id, name in pairs(CONFIG.ALLOWED_PLACES) do
        table.insert(list, ("  - %s (%d)"):format(name, id))
    end
    stop(("This script is not made for this game.\n\nCurrent PlaceId: %d\n\nSupported:\n%s")
        :format(game.PlaceId, table.concat(list, "\n")), CONFIG.KICK_ON_WRONG_PLACE)
end

--==========================================================
--  KEY VALIDATION (Work.ink)
--==========================================================
local function validateKey(key)
    key = tostring(key or ""):gsub("%s+", "")
    if #key < 10 then return false, "Key is too short" end
    if key:find("[^%w%-]") then return false, "Key contains invalid characters" end

    local body = httpGet(API_PREFIX .. key)
    if not body then return false, "Cannot reach key server" end

    local ok, data = pcall(function() return HttpService:JSONDecode(body) end)
    if not ok or type(data) ~= "table" then return false, "Bad server response" end

    if not data.valid then return false, "Key is invalid or expired" end

    local info = data.info or {}
    local byLink = CONFIG.LINK_ID and info.linkId == CONFIG.LINK_ID
    local byOwner = CONFIG.OWNER_USER_ID and info.userId == CONFIG.OWNER_USER_ID
    if not (byLink or byOwner) then
        return false, "Key was not issued for this script"
    end

    if info.expiresAfter and info.expiresAfter > 0 then
        local leftMs = info.expiresAfter - (os.time() * 1000)
        if leftMs <= 0 then return false, "Key has expired" end
        return true, ("Key accepted. Left: %dh %dm")
            :format(math.floor(leftMs / 3600000), math.floor(leftMs % 3600000 / 60000)), info
    end

    return true, "Key accepted", info
end

-- isValid + device bind (one-key-one-person)
local function activateKey(key)
    local ok, msg, info = validateKey(key)
    if not ok then return false, msg end
    local bok, bmsg = bindDevice(key)
    if not bok then
        return false, bmsg or "Key already bound to another device"
    end
    return true, msg, info
end

--==========================================================
--  KEY UI (English) + Discord (disabled)
--==========================================================
local ACCENT = Color3.fromRGB(150, 120, 255)
-- Official-style Discord blurple mark (common catalog asset used in executor GUIs)
local DISCORD_ICON = "rbxassetid://12025413634"

local function corner(o, r)
    local c = Instance.new("UICorner"); c.CornerRadius = UDim.new(0, r); c.Parent = o; return c
end
local function stroke(o, col, th, tr)
    local s = Instance.new("UIStroke"); s.Color = col; s.Thickness = th or 1
    s.Transparency = tr or 0; s.Parent = o; return s
end
local function grad(o, seq, rot)
    local g = Instance.new("UIGradient"); g.Color = seq; g.Rotation = rot or 0; g.Parent = o; return g
end
local function tw(o, props, t, style)
    return TweenService:Create(o,
        TweenInfo.new(t, style or Enum.EasingStyle.Quart, Enum.EasingDirection.Out), props)
end

local function askKey()
    local result = nil
    local conns = {}

    local parent = (gethui and gethui()) or game:GetService("CoreGui")
    local prev = parent:FindFirstChild("ZINKA_KEY_UI")
    if prev then prev:Destroy() end

    local gui = Instance.new("ScreenGui")
    gui.Name = "ZINKA_KEY_UI"
    gui.ResetOnSpawn = false
    gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
    gui.DisplayOrder = 1000
    pcall(function() if syn and syn.protect_gui then syn.protect_gui(gui) end end)
    gui.Parent = parent

    local W, H = 460, 330

    local shadow = Instance.new("ImageLabel")
    shadow.Name = "ZKeyShadow"; shadow.BackgroundTransparency = 1; shadow.ZIndex = 0
    shadow.Image = "rbxassetid://6015897843"
    shadow.ImageColor3 = Color3.fromRGB(0, 0, 0); shadow.ImageTransparency = 0.38
    shadow.ScaleType = Enum.ScaleType.Slice; shadow.SliceCenter = Rect.new(49, 49, 450, 450)
    shadow.AnchorPoint = Vector2.new(0.5, 0.5); shadow.Position = UDim2.fromScale(0.5, 0.5)
    shadow.Size = UDim2.fromOffset(W + 46, H + 46)
    shadow.Parent = gui

    local main = Instance.new("Frame")
    main.AnchorPoint = Vector2.new(0.5, 0.5)
    main.Position = UDim2.fromScale(0.5, 0.5)
    main.Size = UDim2.fromOffset(W - 40, H - 40)
    main.BackgroundColor3 = Color3.fromRGB(15, 15, 21)
    main.BorderSizePixel = 0
    main.ClipsDescendants = true
    main.Active = true
    main.Parent = gui
    corner(main, 16)
    grad(main, ColorSequence.new{
        ColorSequenceKeypoint.new(0, Color3.fromRGB(22, 20, 32)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(12, 12, 18)),
    }, 60)

    local ms = stroke(main, ACCENT, 1.6, 0.4)
    ms.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    TweenService:Create(ms, TweenInfo.new(2.0, Enum.EasingStyle.Sine,
        Enum.EasingDirection.InOut, -1, true), {Transparency = 0.12, Thickness = 2.2}):Play()
    local msGrad = grad(ms, ColorSequence.new{
        ColorSequenceKeypoint.new(0.0, Color3.fromRGB(150, 120, 255)),
        ColorSequenceKeypoint.new(0.5, Color3.fromRGB(120, 220, 255)),
        ColorSequenceKeypoint.new(1.0, Color3.fromRGB(255, 120, 220)),
    }, 0)
    table.insert(conns, RunService.Heartbeat:Connect(function(dt)
        msGrad.Offset = Vector2.new((msGrad.Offset.X + dt * 0.06) % 1, 0)
    end))

    tw(main, {Size = UDim2.fromOffset(W, H)}, 0.28):Play()

    local function syncShadow()
        shadow.Position = main.Position
        shadow.Size = UDim2.fromOffset(main.Size.X.Offset + 46, main.Size.Y.Offset + 46)
    end
    table.insert(conns, main:GetPropertyChangedSignal("Position"):Connect(syncShadow))
    table.insert(conns, main:GetPropertyChangedSignal("Size"):Connect(syncShadow))

    -- header
    local top = Instance.new("Frame")
    top.Size = UDim2.new(1, 0, 0, 62); top.BackgroundColor3 = Color3.fromRGB(12, 12, 18)
    top.BorderSizePixel = 0; top.Parent = main
    corner(top, 16)
    local topFix = Instance.new("Frame")
    topFix.Size = UDim2.new(1, 0, 0, 16); topFix.Position = UDim2.new(0, 0, 1, -16)
    topFix.BackgroundColor3 = top.BackgroundColor3; topFix.BorderSizePixel = 0; topFix.Parent = top

    local title = Instance.new("TextLabel")
    title.BackgroundTransparency = 1
    title.Position = UDim2.fromOffset(22, 9); title.Size = UDim2.fromOffset(280, 26)
    title.Font = Enum.Font.Michroma; title.Text = "ZINKA"; title.TextSize = 23
    title.TextXAlignment = Enum.TextXAlignment.Left; title.TextYAlignment = Enum.TextYAlignment.Top
    title.TextColor3 = Color3.fromRGB(255, 255, 255); title.ZIndex = 3; title.Parent = top
    local tGrad = grad(title, ColorSequence.new{
        ColorSequenceKeypoint.new(0.00, Color3.fromRGB(150, 120, 255)),
        ColorSequenceKeypoint.new(0.25, Color3.fromRGB(255, 120, 220)),
        ColorSequenceKeypoint.new(0.50, Color3.fromRGB(120, 220, 255)),
        ColorSequenceKeypoint.new(0.75, Color3.fromRGB(180, 255, 180)),
        ColorSequenceKeypoint.new(1.00, Color3.fromRGB(150, 120, 255)),
    }, 0)
    table.insert(conns, RunService.Heartbeat:Connect(function(dt)
        tGrad.Offset = Vector2.new((tGrad.Offset.X + dt * 0.35) % 1, 0)
    end))

    local sub = Instance.new("TextLabel")
    sub.BackgroundTransparency = 1
    sub.Position = UDim2.fromOffset(24, 38); sub.Size = UDim2.fromOffset(300, 14)
    sub.Font = Enum.Font.Gotham; sub.Text = "key access  •  secure loader"; sub.TextSize = 11
    sub.TextColor3 = Color3.fromRGB(175, 175, 205)
    sub.TextStrokeColor3 = Color3.fromRGB(8, 8, 12); sub.TextStrokeTransparency = 0.4
    sub.TextXAlignment = Enum.TextXAlignment.Left; sub.ZIndex = 3; sub.Parent = top

    local headRule = Instance.new("Frame")
    headRule.Position = UDim2.fromOffset(0, 61); headRule.Size = UDim2.new(1, 0, 0, 1)
    headRule.BackgroundColor3 = ACCENT; headRule.BackgroundTransparency = 0.55
    headRule.BorderSizePixel = 0; headRule.ZIndex = 4; headRule.Parent = main

    -- Discord button (branding only — disabled / coming soon)
    local discBtn = Instance.new("TextButton")
    discBtn.Size = UDim2.fromOffset(34, 34); discBtn.Position = UDim2.new(1, -86, 0, 14)
    discBtn.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
    discBtn.Text = ""; discBtn.AutoButtonColor = false; discBtn.ZIndex = 3; discBtn.Parent = top
    discBtn.Active = true
    corner(discBtn, 8)
    local discIcon = Instance.new("ImageLabel")
    discIcon.BackgroundTransparency = 1
    discIcon.AnchorPoint = Vector2.new(0.5, 0.5)
    discIcon.Position = UDim2.fromScale(0.5, 0.5)
    discIcon.Size = UDim2.fromOffset(20, 20)
    discIcon.Image = DISCORD_ICON
    discIcon.ZIndex = 4; discIcon.Parent = discBtn
    -- fallback letter if asset missing
    local discFallback = Instance.new("TextLabel")
    discFallback.BackgroundTransparency = 1
    discFallback.Size = UDim2.fromScale(1, 1)
    discFallback.Font = Enum.Font.GothamBold; discFallback.TextSize = 16
    discFallback.Text = "D"; discFallback.TextColor3 = Color3.fromRGB(255, 255, 255)
    discFallback.ZIndex = 3; discFallback.Visible = false; discFallback.Parent = discBtn
    discIcon:GetPropertyChangedSignal("IsLoaded"):Connect(function()
        -- ImageLabel has no IsLoaded on all clients; keep icon, fallback via transparency probe
    end)
    task.delay(1.2, function()
        if discIcon.Parent and discIcon.ImageTransparency >= 0.99 then
            discFallback.Visible = true
        end
    end)
    -- dim overlay to signal disabled
    local discDim = Instance.new("Frame")
    discDim.Size = UDim2.fromScale(1, 1); discDim.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    discDim.BackgroundTransparency = 0.45; discDim.BorderSizePixel = 0
    discDim.ZIndex = 5; discDim.Parent = discBtn
    corner(discDim, 8)

    local closeB = Instance.new("TextButton")
    closeB.Size = UDim2.fromOffset(30, 30); closeB.Position = UDim2.new(1, -42, 0, 16)
    closeB.BackgroundColor3 = Color3.fromRGB(30, 28, 40)
    closeB.Text = "×"; closeB.Font = Enum.Font.GothamBold; closeB.TextSize = 18
    closeB.TextColor3 = Color3.fromRGB(220, 210, 230)
    closeB.AutoButtonColor = false; closeB.ZIndex = 3; closeB.Parent = top
    corner(closeB, 8)

    -- drag
    do
        local dragging, ds, sp
        top.InputBegan:Connect(function(i)
            if i.UserInputType == Enum.UserInputType.MouseButton1 then
                dragging = true; ds = i.Position; sp = main.Position
            end
        end)
        top.InputEnded:Connect(function(i)
            if i.UserInputType == Enum.UserInputType.MouseButton1 then dragging = false end
        end)
        table.insert(conns, UIS.InputChanged:Connect(function(i)
            if dragging and i.UserInputType == Enum.UserInputType.MouseMovement then
                local d = i.Position - ds
                main.Position = UDim2.new(sp.X.Scale, sp.X.Offset + d.X, sp.Y.Scale, sp.Y.Offset + d.Y)
            end
        end))
    end

    local status = Instance.new("TextLabel")
    status.BackgroundTransparency = 1
    status.Position = UDim2.fromOffset(22, 74); status.Size = UDim2.fromOffset(W - 44, 36)
    status.Font = Enum.Font.Gotham; status.TextSize = 13; status.TextWrapped = true
    status.TextXAlignment = Enum.TextXAlignment.Left; status.TextYAlignment = Enum.TextYAlignment.Top
    status.TextColor3 = Color3.fromRGB(175, 175, 205)
    status.Text = "Press Get Key, complete the link steps, then paste your key here."
    status.Parent = main

    local boxBg = Instance.new("Frame")
    boxBg.Position = UDim2.fromOffset(22, 118); boxBg.Size = UDim2.fromOffset(W - 44, 44)
    boxBg.BackgroundColor3 = Color3.fromRGB(24, 22, 34); boxBg.BorderSizePixel = 0
    boxBg.Parent = main
    corner(boxBg, 10)
    local boxStroke = stroke(boxBg, ACCENT, 1, 0.7)

    local box = Instance.new("TextBox")
    box.BackgroundTransparency = 1
    box.Position = UDim2.fromOffset(14, 0); box.Size = UDim2.new(1, -28, 1, 0)
    box.Font = Enum.Font.Code; box.TextSize = 15
    box.TextColor3 = Color3.fromRGB(235, 235, 245)
    box.PlaceholderColor3 = Color3.fromRGB(110, 108, 130)
    box.PlaceholderText = "paste key here"
    box.ClearTextOnFocus = false; box.Text = ""
    box.TextXAlignment = Enum.TextXAlignment.Left
    box.Parent = boxBg
    box.Focused:Connect(function() tw(boxStroke, {Transparency = 0.15}, 0.18):Play() end)
    box.FocusLost:Connect(function() tw(boxStroke, {Transparency = 0.7}, 0.18):Play() end)

    local BW = (W - 44 - 16) / 2

    local getBtn = Instance.new("TextButton")
    getBtn.Position = UDim2.fromOffset(22, 176); getBtn.Size = UDim2.fromOffset(BW, 42)
    getBtn.BackgroundColor3 = Color3.fromRGB(30, 28, 40); getBtn.BorderSizePixel = 0
    getBtn.Font = Enum.Font.GothamMedium; getBtn.TextSize = 14
    getBtn.TextColor3 = Color3.fromRGB(225, 220, 240)
    getBtn.Text = "Get Key"; getBtn.AutoButtonColor = false; getBtn.Parent = main
    corner(getBtn, 10)
    stroke(getBtn, ACCENT, 1, 0.6)

    local okBtn = Instance.new("TextButton")
    okBtn.Position = UDim2.fromOffset(22 + BW + 16, 176); okBtn.Size = UDim2.fromOffset(BW, 42)
    okBtn.BackgroundColor3 = Color3.fromRGB(150, 120, 255); okBtn.BorderSizePixel = 0
    okBtn.Font = Enum.Font.GothamBold; okBtn.TextSize = 14
    okBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
    okBtn.Text = "Submit Key"; okBtn.AutoButtonColor = false; okBtn.Parent = main
    corner(okBtn, 10)
    grad(okBtn, ColorSequence.new{
        ColorSequenceKeypoint.new(0, Color3.fromRGB(160, 130, 255)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(120, 200, 255)),
    }, 15)

    -- Discord row (full-width, disabled)
    local discRow = Instance.new("TextButton")
    discRow.Position = UDim2.fromOffset(22, 228); discRow.Size = UDim2.fromOffset(W - 44, 36)
    discRow.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
    discRow.Text = ""; discRow.AutoButtonColor = false; discRow.Parent = main
    corner(discRow, 10)
    local discRowIcon = Instance.new("ImageLabel")
    discRowIcon.BackgroundTransparency = 1
    discRowIcon.Position = UDim2.fromOffset(12, 8); discRowIcon.Size = UDim2.fromOffset(20, 20)
    discRowIcon.Image = DISCORD_ICON; discRowIcon.ZIndex = 2; discRowIcon.Parent = discRow
    local discRowText = Instance.new("TextLabel")
    discRowText.BackgroundTransparency = 1
    discRowText.Position = UDim2.fromOffset(40, 0); discRowText.Size = UDim2.new(1, -50, 1, 0)
    discRowText.Font = Enum.Font.GothamMedium; discRowText.TextSize = 13
    discRowText.TextXAlignment = Enum.TextXAlignment.Left
    discRowText.TextColor3 = Color3.fromRGB(255, 255, 255)
    discRowText.Text = "Discord  ·  Coming soon"
    discRowText.ZIndex = 2; discRowText.Parent = discRow
    local discRowDim = Instance.new("Frame")
    discRowDim.Size = UDim2.fromScale(1, 1); discRowDim.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    discRowDim.BackgroundTransparency = 0.35; discRowDim.BorderSizePixel = 0
    discRowDim.ZIndex = 3; discRowDim.Parent = discRow
    corner(discRowDim, 10)

    local hint = Instance.new("TextLabel")
    hint.BackgroundTransparency = 1
    hint.Position = UDim2.fromOffset(22, 272); hint.Size = UDim2.fromOffset(W - 44, 34)
    hint.Font = Enum.Font.Gotham; hint.TextSize = 11; hint.TextWrapped = true
    hint.TextXAlignment = Enum.TextXAlignment.Left; hint.TextYAlignment = Enum.TextYAlignment.Top
    hint.TextColor3 = Color3.fromRGB(115, 113, 135)
    hint.Text = "Key is saved locally — you won't need to paste it every time. Enter also submits."
    hint.Parent = main

    local function hover(btn, over, base)
        btn.MouseEnter:Connect(function() tw(btn, {BackgroundColor3 = over}, 0.15):Play() end)
        btn.MouseLeave:Connect(function() tw(btn, {BackgroundColor3 = base}, 0.15):Play() end)
    end
    hover(getBtn, Color3.fromRGB(44, 40, 58), Color3.fromRGB(30, 28, 40))
    hover(okBtn, Color3.fromRGB(175, 148, 255), Color3.fromRGB(150, 120, 255))

    -- cursor (same pattern as before)
    local CURSOR_BIND = "ZINKA_KeyCursor"
    pcall(function() RunService:UnbindFromRenderStep(CURSOR_BIND) end)

    local zCursor = Instance.new("ImageLabel")
    zCursor.Name = "ZCursor"; zCursor.BackgroundTransparency = 1
    zCursor.Size = UDim2.fromOffset(34, 34)
    zCursor.Image = "rbxasset://textures/Cursors/KeyboardMouse/ArrowCursor.png"
    zCursor.ZIndex = 999; zCursor.Visible = false; zCursor.Parent = gui

    local zcGlow = Instance.new("ImageLabel")
    zcGlow.Name = "glow"; zcGlow.BackgroundTransparency = 1
    zcGlow.AnchorPoint = Vector2.new(0.5, 0.5); zcGlow.Position = UDim2.fromScale(0.35, 0.35)
    zcGlow.Size = UDim2.fromOffset(46, 46)
    zcGlow.Image = "rbxasset://textures/Cursors/KeyboardMouse/ArrowCursor.png"
    zcGlow.ImageColor3 = ACCENT; zcGlow.ImageTransparency = 0.4
    zcGlow.ZIndex = 998; zcGlow.Parent = zCursor

    local guiInset = GuiService:GetGuiInset()
    local cursorBound = false
    pcall(function()
        RunService:BindToRenderStep(CURSOR_BIND, Enum.RenderPriority.Last.Value + 1, function()
            if not main.Parent then return end
            if UIS.MouseBehavior ~= Enum.MouseBehavior.Default then
                UIS.MouseBehavior = Enum.MouseBehavior.Default
            end
            if UIS.MouseIconEnabled then
                UIS.MouseIconEnabled = false
            end
            local m = UIS:GetMouseLocation()
            zCursor.Position = UDim2.fromOffset(m.X, m.Y - guiInset.Y)
            zCursor.Visible = true
        end)
        cursorBound = true
    end)

    local function releaseCursor()
        if cursorBound then
            pcall(function() RunService:UnbindFromRenderStep(CURSOR_BIND) end)
            cursorBound = false
        end
        pcall(function() UIS.MouseIconEnabled = true end)
    end

    local function setStatus(text, color)
        status.Text = text
        status.TextColor3 = color or Color3.fromRGB(175, 175, 205)
    end

    local function shutdown(res)
        releaseCursor()
        for _, c in ipairs(conns) do pcall(function() c:Disconnect() end) end
        tw(main, {Size = UDim2.fromOffset(W - 40, H - 40)}, 0.2):Play()
        tw(shadow, {ImageTransparency = 1}, 0.2):Play()
        task.delay(0.22, function() gui:Destroy() end)
        result = res
    end

    local function discordSoon()
        setStatus("Discord soon — invite is not open yet.", Color3.fromRGB(185, 175, 255))
        -- intentionally does NOT open / copy invite while DISCORD_ENABLED == false
        if CONFIG.DISCORD_ENABLED then
            pcall(setclipboard, CONFIG.DISCORD_INVITE)
        end
    end
    discBtn.MouseButton1Click:Connect(discordSoon)
    discRow.MouseButton1Click:Connect(discordSoon)

    getBtn.MouseButton1Click:Connect(function()
        local link = CONFIG.KEY_LINK
        local copied = pcall(setclipboard, link)
        if copied then
            setStatus("Link copied. Open it in your browser, finish the steps, then paste the key.",
                Color3.fromRGB(120, 200, 255))
            getBtn.Text = "Copied ✓"
            task.delay(2, function() if getBtn.Parent then getBtn.Text = "Get Key" end end)
        else
            setStatus("Clipboard unavailable. Ask the owner for the key link.", Color3.fromRGB(235, 185, 95))
        end
    end)

    closeB.MouseButton1Click:Connect(function() shutdown(false) end)

    local busy = false
    local function submit()
        if busy then return end
        local key = (box.Text:gsub("%s+", ""))
        if key == "" then
            setStatus("Empty field — paste your key.", Color3.fromRGB(235, 185, 95))
            return
        end
        busy = true
        okBtn.Text = "Checking…"
        setStatus("Validating key…", Color3.fromRGB(175, 175, 205))

        local ok, msg = activateKey(key)
        if ok then
            setStatus(msg, Color3.fromRGB(125, 230, 150))
            okBtn.Text = "Accepted ✓"
            ACCEPTED_KEY = key
            saveKey(key)
            publishAuth(key)
            task.wait(0.7)
            shutdown(true)
        else
            setStatus("Error: " .. msg, Color3.fromRGB(255, 115, 115))
            okBtn.Text = "Submit Key"
            busy = false
            local base = boxBg.Position
            for _, dx in ipairs({8, -8, 5, -5, 0}) do
                boxBg.Position = base + UDim2.fromOffset(dx, 0)
                task.wait(0.03)
            end
            boxBg.Position = base
        end
    end

    okBtn.MouseButton1Click:Connect(submit)
    box.FocusLost:Connect(function(enter) if enter then submit() end end)

    repeat task.wait(0.1) until result ~= nil
    return result == true
end

--==========================================================
--  KEY FLOW
--==========================================================
local granted = false

local saved = loadSavedKey()
if saved then
    local ok, msg = activateKey(saved)
    if ok then
        granted = true
        ACCEPTED_KEY = saved
        publishAuth(saved)
        notify(msg, 5)
    else
        clearKey()
        notify("Saved key rejected: " .. msg, 6)
    end
end

if not granted then
    granted = askKey()
end

if not granted then
    stop("Access denied — no valid key.\n\nUse Get Key in the loader UI.",
        CONFIG.KICK_ON_NO_KEY)
end

--==========================================================
--  LOAD SCRIPT
--==========================================================
notify(("Game: %s\nLoading script..."):format(placeName), 4)

local function addParam(url, kv)
    return url .. (url:find("?") and "&" or "?") .. kv
end

local scriptUrl = CONFIG.SCRIPT_URL
if ACCEPTED_KEY then scriptUrl = addParam(scriptUrl, "k=" .. ACCEPTED_KEY) end
do
    local hid = getDeviceHwid()
    if hid then scriptUrl = addParam(scriptUrl, "h=" .. hid) end
end
if CONFIG.BUST_CACHE then scriptUrl = addParam(scriptUrl, "v=" .. tostring(os.time())) end

local source = httpGet(scriptUrl)
if not source then stop("Failed to download script. Check your connection.", false) end
if source:match("^%s*<") then stop("Server returned a page instead of code. Check the URL.", false) end

local denied = source:match("^%-%-%[%[DENIED:([%w]+)%]%]")
if denied then
    local infra = denied:match("^source") or denied == "validator" or denied == "noconfig"
    local reasons = {
        badkey    = "Key does not look valid.",
        invalid   = "Key is invalid or expired.",
        foreign   = "Key was not issued for this script.",
        expired   = "Key has expired.",
        bound     = "Key already bound to another device",
        badhwid   = "Device id unavailable — try another executor",
        validator = "Key server is down — try later.",
        noconfig  = "Distributor is misconfigured — contact the owner.",
    }
    local text = reasons[denied] or (infra and "Source unavailable — contact the owner."
                                           or ("Denied: " .. denied))
    if denied == "bound" then
        clearKey()
        stop(text, CONFIG.KICK_ON_NO_KEY)
    elseif infra then
        stop(text, false)
    else
        clearKey()
        stop(text .. "\n\nGet a new key via the loader UI.", CONFIG.KICK_ON_NO_KEY)
    end
end

local chunk, compileErr = loadstring(source, "@" .. CONFIG.NAME)
if not chunk then stop("Compile error:\n" .. tostring(compileErr), false) end

local ranOk, runErr = pcall(chunk)
if not ranOk then stop("Runtime error:\n" .. tostring(runErr), false) end

notify("Script loaded successfully", 4)
